"use client";

import React from 'react';
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
    {
        question: "What is the AI Mock Interviewer?",
        answer: "The AI Mock Interviewer is an advanced platform that helps you practice for job interviews using artificial intelligence. You can create customized mock interviews for specific job roles, answer AI-generated questions using voice or text, and receive comprehensive feedback on your performance to improve your interview skills."
    },
    {
        question: "How does the AI generate interview questions?",
        answer: "Our AI analyzes the job description, position, and your experience level to generate highly relevant and tailored interview questions. The system uses natural language processing to create questions that are specific to the role you're applying for, ensuring realistic interview practice."
    },
    {
        question: "How does the speech recognition work?",
        answer: "We use advanced Web Speech API technology with continuous speech recognition. The system captures your answers in real-time, allows you to pause and continue speaking, and accumulates your responses. Even if you take breaks while speaking, your previous answers are preserved and new speech is appended to them."
    },
    {
        question: "Can I retake interviews with different questions?",
        answer: "Yes! You can use the 'Retake' feature on any completed interview. This will generate a completely new set of questions based on the same job details, allowing you to practice multiple times with fresh content."
    },
    {
        question: "What kind of feedback do I receive?",
        answer: "After completing an interview, you'll receive detailed feedback including: ratings for each answer, constructive suggestions for improvement, analysis of your communication skills, and overall performance metrics. The feedback is generated by AI and tailored to your specific responses."
    },
    {
        question: "Is my interview data saved?",
        answer: "Yes, all your interviews and feedback are saved to your account. You can review them anytime from your dashboard, track your progress over time, and compare performances across different interviews."
    },
    {
        question: "How do I create a new mock interview?",
        answer: "From your dashboard, click the 'Create New Interview' card. Provide the job position, description, and your experience level. The AI will then generate a customized set of questions for you to practice with."
    },
    {
        question: "Can I practice without microphone?",
        answer: "Yes, while we recommend using the speech recognition feature for realistic practice, you can also type your answers if you prefer or if microphone access is not available."
    },
    {
        question: "What browsers are supported?",
        answer: "For speech recognition, we recommend using Chrome, Edge, or Safari as they have the best support for the Web Speech API. The basic functionality works on all modern browsers."
    },
    {
        question: "Is there a limit to how many interviews I can create?",
        answer: "Currently, there are no limits on the number of interviews you can create. Practice as much as you need to feel confident for your real interviews!"
    }
];

function FAQsPage() {
    return (
        <div className="p-10">
            <h2 className="text-3xl font-bold text-center mb-6">Frequently Asked Questions</h2>
            <Accordion type="single" collapsible className="w-full max-w-2xl mx-auto">
                {faqs.map((faq, index) => (
                    <AccordionItem value={`item-${index}`} key={index}>
                        <AccordionTrigger>{faq.question}</AccordionTrigger>
                        <AccordionContent>{faq.answer}</AccordionContent>
                    </AccordionItem>
                ))}
            </Accordion>
        </div>
    );
}

export default FAQsPage;